# Generated by Django 3.0.8 on 2020-08-02 19:05

import base.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=base.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=base.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-ruler-pencil', 'almofada'), ('lni-customer', 'baby'), ('lni-support', 'outros'), ('lni-grid-alt', 'pet')], max_length=50, verbose_name='Icone'),
        ),
    ]
