# Generated by Django 3.0.8 on 2020-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200802_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-grid-alt', 'pet'), ('lni-customer', 'baby'), ('lni-support', 'outros'), ('lni-ruler-pencil', 'almofada')], max_length=50, verbose_name='Icone'),
        ),
    ]
